(set! allowables 
      '((a _epsilon_ er axr axh ax ah aw ay ae ao aa ix ih uh ey eh ih )
        (b _epsilon_ b )
        (c _epsilon_ s k ch sh k-w )
        (d _epsilon_ d dx t jh jh )
        (e _epsilon_ eh er ey ix ih iy r-ih aa ah ax axh axr axr-r uw ux oy y-ux )
        (f _epsilon_ f v )
        (g _epsilon_ jh g zh f )
        (h _epsilon_ hh hv )
        (i _epsilon_ ay ae ah ax axr axh ih ix iy y y-uw y-ux er )
        (j _epsilon_ jh )
        (k _epsilon_ k )
        (l _epsilon_ l el eh-l )
        (m _epsilon_ m em ax-m ix-m m-ax m-ah )
        (n _epsilon_ n en nx ng )
        (o _epsilon_ ow oy ux uh ih ix er uw aa ax axh ah axr aw ao ay axr iy w-ah w-aa w-ae )
        (p _epsilon_ p f )
        (q _epsilon_ k w )
        (r _epsilon_ r r-r )
        (s _epsilon_ s z sh zh s z ah-s ah-z )
        (t _epsilon_ t dh dx th s q d ch th sh )
        (u _epsilon_ uw uh ux ah ax axr ih y-axr y-ux y-uh y-ah er w )
        (v _epsilon_ v )
        (w _epsilon_ w hh-w v )
        (x _epsilon_ k-s g-s s sh k-sh g-z g-zh z )
        (y _epsilon_ y jh zh ay ah ix iy ih w er )
        (z _epsilon_ z s zh )
        (# #)))
