;; INTSINT intonation model autotrained by festvox
;; intonation.S50.tree
(set! cstr_pl_em::intsint_tree '
((stress is 0)
 ((0))
 ((p.p.p.R:Intonation.daughter1.name is 0)
  ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 0)
   ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is 0)
    ((syl_vowel is a)
     ((M))
     ((syl_vowel is e)
      ((M))
      ((syl_vowel is u)
       ((T))
       ((syl_vowel is o) ((M)) ((syl_vowel is i) ((M)) ((T)))))))
    ((p.p.R:Intonation.daughter1.name is 0)
     ((syl_vowel is a)
      ((M))
      ((R:SylStructure.daughtern.ph_vfront is 1)
       ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is s)
        ((M))
        ((T)))
       ((syl_vowel is u)
        ((M))
        ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is s)
         ((M))
         ((T))))))
     ((p.p.R:Intonation.daughter1.name is T)
      ((L))
      ((R:SylStructure.daughtern.ph_vfront is 1) ((L)) ((H))))))
   ((R:SylStructure.parent.R:Word.n.pbreak is NB)
    ((p.p.p.p.R:Intonation.daughter1.name is 0)
     ((p.p.R:Intonation.daughter1.name is 0)
      ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 1)
       ((syl_vowel is a)
        ((B))
        ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is 0)
         ((R:SylStructure.daughtern.ph_vfront is 3) ((M)) ((B)))
         ((syl_vowel is o)
          ((B))
          ((R:SylStructure.daughtern.ph_vfront is 1)
           ((B))
           ((syl_vowel is u) ((T)) ((M)))))))
       ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
        ((B))
        ((R:SylStructure.daughtern.ph_vfront is 3)
         ((B))
         ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is s)
          ((B))
          ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 3)
           ((L))
           ((U)))))))
      ((p.p.R:Intonation.daughter1.name is B)
       ((H))
       ((syl_vowel is e)
        ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is 0)
         ((B))
         ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 1)
          ((B))
          ((L))))
        ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is n)
         ((syl_vowel is a) ((B)) ((syl_vowel is o) ((B)) ((D))))
         ((p.p.R:Intonation.daughter1.name is L)
          ((syl_vowel is a) ((U)) ((H)))
          ((syl_vowel is a)
           ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 1)
            ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is 0)
             ((B))
             ((L)))
            ((B)))
           ((p.p.R:Intonation.daughter1.name is H)
            ((D))
            ((p.p.R:Intonation.daughter1.name is T)
             ((L))
             ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 1)
              ((R:SylStructure.daughtern.ph_vfront is 3) ((U)) ((L)))
              ((B)))))))))))
     ((p.p.p.p.R:Intonation.daughter1.name is B)
      ((p.p.R:Intonation.daughter1.name is 0) ((H)) ((L)))
      ((p.p.R:Intonation.daughter1.name is 0)
       ((R:SylStructure.daughtern.ph_vfront is 1)
        ((syl_vowel is I)
         ((B))
         ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
          ((L))
          ((B))))
        ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is s)
         ((B))
         ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
          ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is f)
           ((L))
           ((B)))
          ((B)))))
       ((p.p.R:Intonation.daughter1.name is B)
        ((H))
        ((p.p.R:Intonation.daughter1.name is L)
         ((H))
         ((syl_vowel is a)
          ((B))
          ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
           ((R:SylStructure.daughtern.ph_vfront is 3) ((L)) ((B)))
           ((L)))))))))
    ((R:SylStructure.parent.R:Phrase.n.parent.name is 0)
     ((B))
     ((R:SylStructure.daughtern.ph_vfront is 2)
      ((L))
      ((syl_vowel is o)
       ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
        ((L))
        ((p.p.R:Intonation.daughter1.name is 0) ((L)) ((U))))
       ((p.p.p.p.R:Intonation.daughter1.name is 0)
        ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
         ((S))
         ((R:SylStructure.daughtern.ph_vfront is -)
          ((L))
          ((syl_vowel is e) ((S)) ((D)))))
        ((p.p.p.p.R:Intonation.daughter1.name is B)
         ((U))
         ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 1)
          ((D))
          ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
           ((L))
           ((S)))))))))))
  ((R:SylStructure.parent.R:Word.n.pbreak is NB)
   ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 1)
    ((R:SylStructure.daughtern.ph_vfront is -)
     ((L))
     ((syl_vowel is o)
      ((B))
      ((R:SylStructure.daughtern.ph_vfront is 2)
       ((B))
       ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is f)
        ((D))
        ((B))))))
    ((p.p.p.R:Intonation.daughter1.name is B)
     ((syl_vowel is a)
      ((H))
      ((syl_vowel is o)
       ((H))
       ((R:SylStructure.daughtern.ph_vfront is 1)
        ((syl_vowel is e) ((U)) ((H)))
        ((H)))))
     ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 3)
      ((R:SylStructure.daughtern.ph_vfront is 1)
       ((B))
       ((R:SylStructure.daughtern.ph_vfront is -) ((L)) ((B))))
      ((syl_vowel is a)
       ((B))
       ((syl_vowel is o)
        ((B))
        ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is 0)
         ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 2)
          ((R:SylStructure.daughtern.ph_vfront is 1) ((B)) ((D)))
          ((B)))
         ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is n)
          ((L))
          ((R:SylStructure.parent.R:Word.p.p.word_numsyls is 0)
           ((L))
           ((p.p.p.R:Intonation.daughter1.name is L) ((U)) ((B)))))))))))
   ((R:SylStructure.parent.R:Word.n.pbreak is 0)
    ((p.p.p.R:Intonation.daughter1.name is S)
     ((B))
     ((p.p.p.R:Intonation.daughter1.name is U)
      ((B))
      ((p.p.p.R:Intonation.daughter1.name is D)
       ((B))
       ((p.p.p.R:Intonation.daughter1.name is B) ((S)) ((B))))))
    ((syl_vowel is o)
     ((D))
     ((p.p.p.R:Intonation.daughter1.name is B)
      ((U))
      ((syl_vowel is e)
       ((S))
       ((R:SylStructure.daughter1.R:Segment.p.p.ph_ctype is 0)
        ((L))
        ((R:SylStructure.daughtern.ph_vfront is 2) ((L)) ((B)))))))))))
)


(provide 'cstr_pl_intsint_tree)


