/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include <stdlib.h>
#include "cst_lts.h"

const char * const cmu_lts_phone_table_english[75] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "ey1",
    "aa0",
    "aw1",
    "ax",
    "ao1",
    "er0",
    "ay0",
    "ey0",
    "ih1",
    "ae1",
    "aw0",
    "ow0",
    "eh0",
    "ow1",
    "iy1",
    "ao0",
    "ih0",
    "w-ey1",
    "ae0",
    "ah1",
    "ay1",
    "b",
    "ch",
    "s",
    "k",
    "sh",
    "t-s",
    "d",
    "t",
    "jh",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "uw0",
    "y-uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax-l",
    "ax-m",
    "m",
    "m-ae1",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "r",
    "z",
    "th",
    "dh",
    "y-uh1",
    "y-er1",
    "y-er0",
    "y-uh0",
    "y-ax",
    "ax-w",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table_english[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index_english[27] = 
{
    0, /* a */
    4917, /* b */
    5029, /* c */
    5620, /* d */
    5761, /* e */
    10366, /* f */
    10447, /* g */
    10948, /* h */
    11170, /* i */
    14706, /* j */
    14823, /* k */
    14838, /* l */
    15162, /* m */
    15183, /* n */
    15451, /* o */
    18808, /* p */
    18841, /* q */
    18842, /* r */
    20538, /* s */
    21483, /* t */
    21829, /* u */
    23496, /* v */
    23504, /* w */
    23628, /* x */
    23673, /* y */
    24078, /* z */
    0
};

