(utt.save.wave (SayText "a przecierz gdyby tego nie uczynil/ badania byl/yby opuz~nione.") "badania.wav")
(utt.save.wave (SayText "ceny wynajmu mieszkan~ na podstawie kturych zostal/ przygotowany niniejszy raport zawierajo~ opl/aty czynszowe. Ich wysokos~c~ jest uzalerzniona przede wszystkim od powierzchni oraz liczby osub w nim mieszkacjo~cych.") "ceny.wav")
(utt.save.wave (SayText "byl/ to czl/owiek jeszcze dos~c~ ml/ody z twarzo~ wyrzez~biono~ jakby w drzewie.") "czlow.wav")
(utt.save.wave (SayText "gruszki jak dzbany i s~liczne jabl/ka migal/y mie~dzy strzechami.") "gruszki.wav")
(utt.save.wave (SayText "jaracz zdobyl/ bro~zowy medal w najbardziej prestirzowej kategorii open.") "jaracz.wav")
(utt.save.wave (SayText "do podzl/otoryjskich kamieniol/omuw dzien~ i noc jerzdzo~ dziesio~tki cie~rzaruwek.") "kamien.wav")
(utt.save.wave (SayText "szok l/zy wytykanie palcami przez otoczenie.") "lzy.wav")
(utt.save.wave (SayText "jest to odporny na warunki pogodowe cyfrowy odtwarzacz dz~wie~ko~w." ) "play.wav")
(utt.save.wave (SayText "ktos~ siadl/ mu na plecach i poterzno~ dl/onio~ przydusil/ l/eb do ziemi.") "siad.wav")
(utt.save.wave (SayText "dwa dni po s~mierci brata miarzdz~y go w samochodzie ogromna cie~rzaruwka.") "smierc.wav")
(utt.save.wave (SayText "jednak jego nazwisko widnieje nadal na szyldzie zespol/u adwokackiego.") "szyld.wav")
(utt.save.wave (SayText "w najblirzszych planach Telewizji Polskiej jest uruchomienie, prawdopodobnie na przel/omie kwietnia i maja, kanal/u tematycznego Kultura.") "kultura.wav" )
(utt.save.wave (SayText "Obnirzona o centymetr Laguna giete z dwustu pie~cioma koniami mechanicznymi nie ma problemu ze rzwawym przyspieszaniem. Turbodol/adowanie robi swoje.") "rano.wav")
(utt.save.wave (SayText "jest to odporny na warunki pogodowe cyfrowy odtwarzacz dz~wie~kuw" ) "play.wav")
(utt.save.wave (SayText "po za okres~lonymi wyjo~tkami tylko w zakresie okres~lonym w tej licencji przez stosowne przepisy urzytkownik nie morze kopiowac~ i dekompilowac~ i rozmontowywac~ lub  tworzyc~ wl/asnego oprogramowania ") "licencja.wav")
(utt.save.wave (SayText "ceny wynajmu mieszkan~ na podstawie kturych zostal/ przygotowany niniejszy raport zawierajo~ opl/aty czynszowe. ich wysokos~c~ jest uzalerzniona przede wszystkim od powierzchni oraz liczby osub w nim mieszkajo~cych.") "ceny_new.wav")
(utt.save.wave (SayText "Durze wrarzenie robio~ plastiki kokpitu. W tej klasie trudno znalez~c~ podobnej jakos~ci tworzywa. Audi, beemwu, Mercedes i spul/ka majo~ temat do przemys~len~.") "audi.wav")
(utt.save.wave (SayText "Zaraz po wczorajszej manifestacji milicja aresztowal/a Marine~ Bogdanowicz oraz szefa zwio~zku kupcuw bazarowych.") "kupiec.wav")
