#!/bin/sh
"true" ; exec festival --script $0 $*

(set_backtrace t)

(define (dump_tree_nodes file tree label)
"Dump the nodes of the tree into the file f using label as a base"
    (if (not (null? tree))    
	(begin 
        (format file "%s [label=\"%l\"];\n" label (car tree))
        (dump_tree_nodes file (car (cdr tree)) (string-append label "l"))
	(dump_tree_nodes file (car (cdr (cdr tree))) (string-append label "r")))
    )
)

(define (dump_tree_transitions file tree label)
"Dump the nodes of the tree into the file f using label as a base"
    (if (not (null? (car (cdr tree))))    
	(begin 
        (format file "%s -- %sl;\n" label label)
	(format file "%s -- %sr;\n" label label)
        (dump_tree_transitions file (car (cdr tree)) (string-append label "l"))
	(dump_tree_transitions file (car (cdr (cdr tree))) (string-append label "r")))
    )
)

(define (main)
    (let ((tree (car (load (car argv) t)))
          (file (fopen "tree.dot" "w")))
   
    (format file "graph tree {\n")
    
    (dump_tree_nodes file tree "root")
    (dump_tree_transitions file tree "root")
    
    (format file "}")
    (fclose file)
    (system "dot -Tjpg -o tree.jpg tree.dot")
;;  (system "rm tree.dot")
))

(main)
